import puppeteer from 'puppeteer';
const browser = await puppeteer.launch();
const page = await browser.newPage();
page.on('console', msg => console.log('PAGE LOG:', msg.text()));
page.on('pageerror', error => console.log('PAGE ERROR:', error.message));
await page.goto('http://localhost:5173');
await new Promise(r => setTimeout(r, 2000));
const btn = await page.$('.chatbot-toggle');
await btn.click();
await new Promise(r => setTimeout(r, 500));
const mood = await page.$('.chat-chip');
await mood.click();
await new Promise(r => setTimeout(r, 1000));
const genre = await page.$('.btnGhost--sm');
await genre.click();
await new Promise(r => setTimeout(r, 2000));
await browser.close();
